package com.alessandro.astages.api.reload;

public enum AStagesReloadPhase {
    INITIAL,

    BEFORE_MANAGERS_BEFORE_SCRIPTS_RELOAD,
    AFTER_MANAGERS_BEFORE_SCRIPTS_RELOAD,

    BEFORE_JAVA_REGISTRATION_BEFORE_SCRIPTS_RELOAD,
    AFTER_JAVA_REGISTRATION_BEFORE_SCRIPTS_RELOAD,

    BEFORE_SCRIPTS_RELOAD,
    AFTER_SCRIPTS_RELOAD,

    BEFORE_JAVA_REGISTRATION_AFTER_SCRIPTS_RELOAD,
    AFTER_JAVA_REGISTRATION_AFTER_SCRIPTS_RELOAD,

    BEFORE_MANAGERS_AFTER_SCRIPTS_RELOAD,
    AFTER_MANAGERS_AFTER_SCRIPTS_RELOAD,

    END

    /*
    public enum BeforeScripts {
        BEFORE_MANAGERS,
        AFTER_MANAGERS,
        BEFORE_JAVA_REGISTRATION,
        AFTER_JAVA_REGISTRATION;
    }

    public enum AfterScripts {
        BEFORE_MANAGERS,
        AFTER_MANAGERS,
        BEFORE_JAVA_REGISTRATION,
        AFTER_JAVA_REGISTRATION;
    }
     */
}