name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Features'
    labels:
      - feat

  - title: 'Bug Fixes'
    labels:
      - fix

  - title: 'API Changes'
    labels:
      - api

  - title: 'Removed'
    labels:
      - removed

  - title: 'Performance Improvements'
    labels:
      - perf

change-template: '- $TITLE'

replacers:
  - search: '^(feat|fix|api|perf|performance|removed|chore)(\([^)]+\))?!?:\s*'
    replace: ''

template: |
  ## Changelog
  $CHANGES
