buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }

    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'maven-publish'
    id 'org.spongepowered.mixin' version "0.7.+"
}

apply plugin: 'org.spongepowered.mixin'

group = mod_group_id
version = mod_version

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}


minecraft {
    mappings channel: 'parchment', version: '2023.09.03-1.20.1'
    copyIdeResources = true
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        // applies to all the run configs below
        configureEach {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        server {
            workingDirectory project.file('run-server')

            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }

        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            workingDirectory project.file('run-data')

            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"

    config "${mod_id}.mixins.json"
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        url = "https://maven.architectury.dev"
        content {
            includeGroup "dev.architectury"
        }
    }

    maven {
        url = "https://maven.saps.dev/minecraft"
        content {
            includeGroup "dev.latvian.mods"
        }
    }

    maven {
        // location of the maven that hosts JEI files before January 2023
        name = "Progwml6's maven"
        url = "https://dvs1.progwml6.com/files/maven/"
    }

    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }

    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }

    maven { // Thermal
        // Human Browsable: https://nexus.covers1624.net/#browse/browse:cofh-releases
        url 'https://maven.covers1624.net/'
        content {
            includeGroup 'com.teamcofh'
        }
    }

    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    // Botania
    // compileOnly fg.deobf("curse.maven:botania-225643:5594997")
    // implementation fg.deobf("curse.maven:botania-225643:5002307")
    // implementation fg.deobf("curse.maven:curios-309927:5680164")
    // implementation fg.deobf("curse.maven:patchouli-306770:4966125")

    // Mekanism
    // compileOnly fg.deobf("curse.maven:mekanism-268560:5662583")
    // implementation fg.deobf("curse.maven:mekanism-268560:5662583")

    // Thermal
    // implementation fg.deobf("curse.maven:thermal-expansion-69163:5372749")
    // implementation fg.deobf("curse.maven:thermal-foundation-222880:5443583")
    // implementation fg.deobf("curse.maven:cofh-core-69162:5374122")
    // implementation fg.deobf("com.teamcofh:thermal_core:${mc_version}-11.1.0")
    // compileOnly fg.deobf("com.teamcofh:cofh_core:${minecraft_version}-${cofh_core_version}")
    // compileOnly fg.deobf("com.teamcofh:thermal_core:${minecraft_version}-${thermal_core_version}")
    // implementation fg.deobf("com.teamcofh:thermal_foundation:${minecraft_version}-${thermal_foundation_version}")
    // compileOnly fg.deobf("com.teamcofh:thermal_expansion:${minecraft_version}-${thermal_expansion_version}")

    // Create
    // implementation fg.deobf("curse.maven:create-328085:5838779")
    // implementation fg.deobf("curse.maven:create-328085:5838779")

    // In Control!
    compileOnly fg.deobf("curse.maven:in-control-257356:5932870")

    // Example mod dependency with JEI - using fg.deobf() ensures the dependency is remapped to your development mappings
    // The JEI API is declared for compile time use, while the full JEI artifact is used at runtime
    // compileOnly fg.deobf("mezz.jei:jei-${mc_version}-common-api:${jei_version}")
    // compileOnly fg.deobf("mezz.jei:jei-${mc_version}-forge-api:${jei_version}")
    // runtimeOnly fg.deobf("mezz.jei:jei-${mc_version}-forge:${jei_version}")

    // Example mod dependency using a mod jar from ./libs with a flat dir repository
    // This maps to ./libs/coolmod-${mc_version}-${coolmod_version}.jar
    // The group id is ignored when searching -- in this case, it is "blank"
    // implementation fg.deobf("blank:coolmod-${mc_version}:${coolmod_version}")

    // For more info:
    // http://www.gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html
    // http://www.gradle.org/docs/current/userguide/dependency_management.html

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'


    implementation fg.deobf("dev.latvian.mods:kubejs-forge:2001.6.5-build.14")
    implementation fg.deobf("dev.latvian.mods:rhino-forge:2001.2.2-build.18")
    implementation fg.deobf("dev.architectury:architectury-forge:9.1.13")

    // implementation fg.deobf("curse.maven:the-twilight-forest-227639:5468648")

    // compileOnly(fg.deobf("dev.latvian.mods:kubejs-forge:2001.6.5-build.14"))
    // compileOnly(fg.deobf("dev.latvian.mods:rhino-forge:2001.2.2-build.18"))
    // compileOnly(fg.deobf("dev.architectury:architectury-forge:9.1.13"))

    // compile against the JEI API but do not include it at runtime
    compileOnly(fg.deobf("mezz.jei:jei-${mc_version}-forge-api:${jei_version}"))
    // at runtime, use the full JEI jar for Forge
    implementation fg.deobf("mezz.jei:jei-${mc_version}-forge:${jei_version}")
    // compileOnly(fg.deobf("mezz.jei:jei-${mc_version}-forge:${jei_version}"))

    implementation fg.deobf("curse.maven:jade-324717:5339264")

    implementation fg.deobf("curse.maven:probejs-585406:5227399")

    // implementation fg.deobf("curse.maven:ftb-quests-forge-289412:5363570")
    // implementation fg.deobf("curse.maven:ftb-quests-forge-289412:5378300")
    // implementation fg.deobf("curse.maven:ftb-quests-forge-289412:5418359")
    // implementation fg.deobf("curse.maven:ftb-quests-forge-289412:5513826")
    // implementation fg.deobf("curse.maven:ftb-quests-forge-289412:5816794")
    // implementation fg.deobf("curse.maven:ftb-quests-forge-289412:5543955")
    // implementation fg.deobf("curse.maven:ftb-library-forge-404465:6016763")
    // implementation fg.deobf("curse.maven:ftb-teams-forge-404468:5267190")

    // compileOnly fg.deobf("dev.emi:emi-forge:${emi_version}:api")
    // compileOnly fg.deobf("dev.emi:emi-forge:${emi_version}")
    // Just Enough Resources
    implementation fg.deobf("curse.maven:just-enough-resources-jer-240630:5057220")
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [minecraft_version   : minecraft_version, minecraft_version_range: minecraft_version_range,
                             forge_version       : forge_version, forge_version_range: forge_version_range,
                             loader_version_range: loader_version_range,
                             mod_id              : mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
                             mod_authors         : mod_authors, mod_description: mod_description,]

    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes(["Specification-Title"     : mod_id,
                    "Specification-Vendor"    : mod_authors,
                    "Specification-Version"   : "1", // We are version 1 of ourselves
                    "Implementation-Title"    : project.name,
                    "Implementation-Version"  : project.jar.archiveVersion,
                    "Implementation-Vendor"   : mod_authors,
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")])
    }

    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
