# File: .cliff.toml

[changelog]
header = """
## [{{ env.VERSION }}] - {{ now("UTC").format("%d-%m-%Y") }}
"""
body = """
{% if groups.Added %}
### Added
{% for commit in groups.Added %}
- **{{ commit.message | upper_first }}**
{% endfor %}
{% endif %}

{% if groups.Changed %}
### Changes
{% for commit in groups.Changed %}
- **{{ commit.message | upper_first }}**
{% endfor %}
{% endif %}

{% if groups.Fixed %}
### Fixed
{% for commit in groups.Fixed %}
- **{{ commit.message | upper_first }}**
{% endfor %}
{% endif %}

{% if groups.Technical %}
### Technical
{% for commit in groups.Technical %}
- **{{ commit.message | upper_first }}**
{% endfor %}
{% endif %}
"""

footer = """
This build includes experimental features that MUST be manually activated.
"""

[[group]]
title = "Added"
pattern = "^(feat|add)"

[[group]]
title = "Changed"
pattern = "^(change|refactor)"

[[group]]
title = "Fixed"
pattern = "^(fix)"

[[group]]
title = "Technical"
pattern = "^(chore|perf|style|docs|test)"

[git]
conventional_commits = true
filter_unconventional = false
