name: Bug Report
description: Report a bug with AStages
labels: [ bug ]
body:
  - type: dropdown
    id: loader-type
    attributes:
      label: Loader Type
      options:
        - Forge
        - NeoForge
    validations:
      required: true

  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Version
      options:
        - 1.20.1
        - 1.21.1
    validations:
      required: true

  - type: dropdown
    id: astages-version
    attributes:
      label: AStages Version
      options:
        - 0.1.0
        - 0.1.1
        - 0.2.0
        - 0.2.1
        - 0.2.2
        - 0.3.0
        - 0.4.0
        - 0.4.1
        - 0.5.0
        - 0.6.0
        - 0.6.1
        - 0.7.0
        - 0.8.0
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Issue Description"

  - type: textarea
    id: description
    attributes:
      label: Describe your issue
    validations:
      required: true

  - type: input
    id: logs
    attributes:
      label: Crash report/logs
      description: Paste a link to the crash report or latest.log, if required