name: Bug Report
description: Report a bug with AStages
labels: [ bug ]
body:
  - type: dropdown
    id: loader-type
    attributes:
      label: Loader Type
      options:
        - Forge
        - NeoForge
    validations:
      required: true

  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Version
      options:
        - 1.20.1
        - 1.21.1
    validations:
      required: true

  - type: input
    id: astages-version
    attributes:
      label: AStages Version
      placeholder: "Ex: 0.8.0"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Issue Description"

  - type: textarea
    id: description
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true

  - type: input
    id: logs
    attributes:
      label: Crash report/logs
      description: Paste a link to the crash report or latest.log, if required.