name: Changelog
on: [workflow_dispatch]

jobs:
  build_changelog:
    environment: Token
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest stable tag
        id: latest_tag
        run: |
          TAG=$(git tag --list 'v*' \
            | grep -Ev 'alpha|beta|rc' \
            | sort -V \
            | tail -n 1)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Generate release changelog
        id: changelog
        uses: janheinrichmerker/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          pullRequests: true
          dateFormat: "%d-%m-%Y"
          issues: false
          unreleased: true
          sinceTag: "${{ steps.latest_tag.outputs.tag }}"
#          unreleasedOnly: true
#          futureRelease: "2.0.0-1.20.1"
          stripGeneratorNotice: true
          author: false
          configureSections: |
            {
              "API": {
                "labels": ["api"]
              },
              "Added": {
                "labels": ["feat"]
              },
              "Removed": {
                "labels": ["removed"]
              },
              "Fixed": {
                "labels": ["fix"]
              },
              "Performance Improvements": {
                "labels": ["perf"]
              }
            }

      - name: Remove title
        run: |
          sed -i '/^# Changelog$/d' CHANGELOG.md

      - name: Remove "Merged pull requests" header
        run: |
          sed -i '/^\*\*Merged pull requests:\*\*/d' CHANGELOG.md

      - name: Remove "Full Changelog" lines
        run: |
          sed -i '/Full Changelog/d' CHANGELOG.md

#      - name: Clean PR titles
#        run: |
#          sed -i 's/^-\s*api: \s*/- /i' CHANGELOG.md
#          sed -i 's/^-\s*fix: \s*/- /i' CHANGELOG.md
#          sed -i 's/^-\s*feat: \s*/- /i' CHANGELOG.md
#          sed -i 's/^-\s*removed: \s*/- /i' CHANGELOG.md
#          sed -i 's/^-\s*perf: \s*/- /i' CHANGELOG.md

      - name: Upload changelog
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: CHANGELOG.md