name: Changelog Builder Action
on: [workflow_dispatch]

jobs:
  build_changelog:
    environment: Token
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Complex Configuration"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v6
        with:
          configuration: "configuration_complex.json"
          # repo: "AStages"
          ignorePreReleases: "false"
          fromTag: "v2.0.0-alpha.3"
          # toTag: "v2.0.0-alpha.5"
          baseBranch: '1.20.X'
          token: ${{ secrets.GITHUB_TOKEN }}
          outputFile: "CHANGELOG.md"

      - name: Upload changelog
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: CHANGELOG.md