name: Changelog
on: [workflow_dispatch]

jobs:
  build_changelog:
    environment: Token
    runs-on: ubuntu-latest

    steps:
      - name: Generate release changelog
        id: changelog
        uses: janheinrichmerker/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          pullRequests: true
          issues: true
          unreleased: true
#          merge_prefix: ""
          stripGeneratorNotice: true
          author: false
          configureSections: |
            {
              "API": {
                "labels": ["api"]
              },
              "Added": {
                "labels": ["added", "feature"]
              },
              "Removed": {
                "labels": ["removed"]
              },
              "Fixed": {
                "labels": ["bug", "fix"]
              },
              "Compatibility": {
                "labels": ["compatibility", "integration"]
              },
              "Internal": {
                "labels": ["internal", "refactor"]
              }
            }
      - name: Remove "Merged pull requests" header
        run: |
          sed -i '/^\*\*Merged pull requests:\*\*/d' CHANGELOG.md

      - name: Remove "Full Changelog" lines
        run: |
          sed -i '/Full Changelog/d' CHANGELOG.md

      - name: Upload changelog
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: CHANGELOG.md