name: Changelog
on: [workflow_dispatch]

jobs:
  build_changelog:
    environment: Token
    runs-on: ubuntu-latest

    steps:
      - name: Generate release changelog
        id: changelog
        uses: janheinrichmerker/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          sinceTag: false
#          pullRequests: true
#          issues: true
          unreleased: true
          configureSections: |
            {
              "API": {
                "labels": ["api"]
              },
              "Added": {
                "labels": ["added", "feature"]
              },
              "Removed": {
                "labels": ["removed"]
              },
              "Fixed": {
                "labels": ["bug", "fix"]
              },
              "Compatibility": {
                "labels": ["compatibility", "integration"]
              },
              "Internal": {
                "labels": ["internal", "refactor"]
              }
            }