name: Generate Changelog

on:
  workflow_dispatch:
    inputs:
      from:
        description: "Starting Commit/Tag (es: v1.3.0 o SHA)"
        required: true
        default: ""

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read version
        id: version
        run: |
          VERSION=$(grep '^mod_version' gradle.properties | cut -d'=' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install git-cliff
        uses: orhun/git-cliff-action@v1

      - name: Generate CHANGELOG
        env:
          MOD_VERSION: ${{ steps.version.outputs.version }}
        run: |
          if [ -z "${{ github.event.inputs.from }}" ]; then
            git-cliff --context version=$MOD_VERSION --output CHANGELOG.md
          else
            git-cliff ${{ github.event.inputs.from }}..HEAD --context version=$MOD_VERSION --output CHANGELOG.md
          fi

      - name: Commit and push
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add CHANGELOG.md
          git commit -m "docs(changelog): update changelog for version ${{ steps.version.outputs.version }}"
          git push
